name: UI Tests

on:
  push:
    branches:
    - lab
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge, anaconda
    - name: Create the conda environment with ipytablewidgets
      run: |
        git clone https://github.com/progressivis/ipytablewidgets.git
        cd ipytablewidgets
        conda env create -q python=3.9 -f environment.yml -n ipyvega
        cd ..
    - name: Run tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate ipyvega
        python -c 'import ipytablewidgets'
        conda install poetry -c conda-forge -y	
        poetry install
        conda install nodejs=14 -c conda-forge # downgraded to avoid ERR_OSSL_EVP_UNSUPPORTED
        conda install jupyterlab=3.0.1 -c conda-forge # required 4 galata
        conda install yarn -c conda-forge -y
        yarn install
        yarn run build
        which python
        python --version
        echo 'import traitlets'
        python -c 'import traitlets'
        echo 'import traitlets.utils'
        python -c 'import traitlets.utils'
        echo 'import traitlets.utils.descriptions'
        python -c 'import traitlets.utils.descriptions'
        echo 'from traitlets.utils.descriptions import describe'
        python -c 'from traitlets.utils.descriptions import describe'
        echo 'jupyter labextension install .'
        jupyter labextension install .
        cd ui-tests/
        jupyter trust tests/notebooks/NBTest.ipynb	
        yarn
        yarn run start-jlab:detached
        yarn run test
    - name: Upload output file
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cell-artifact
        path: ui-tests/test-output/test/screenshots/vega_cell_*.png
