name: UI Tests

on:
  push:
    branches:
      - master
      - pandas-15
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python }}

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.3.2

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install Python dependencies
        run: |
          poetry install
          python -m pip install jupyterlab-widgets==1.1.2
          python -m pip install jupyterlab==3.6.1

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Run tests
        run: |
          jupyter labextension install .
          jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
          cd ui-tests/
          yarn
          yarn start-jlab:detached
          sleep 10
          yarn test
      - name: Upload output file
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cell-artifact
          path: ui-tests/test-output/test/screenshots/vega_cell_*.png
