name: UI Tests

on:
  push:
    branches:
      - condaless
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    name: Python ${{ matrix.python }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python }}

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.4

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install Python dependencies
        run: poetry install

      - run: poetry run jupyter labextension install .
      - run: poetry install --extras "jupyterlab"
      - name: Setup Node
        uses: actions/setup-node@v2.5.1

      - name: Run tests
      run: |
        yarn install
        yarn run build
        cd ui-tests/
        yarn
        yarn run start-jlab:detached
        yarn run test
    - name: Upload output file
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cell-artifact
        path: ui-tests/test-output/test/screenshots/vega_cell_*.png
